--create database 

CREATE DATABASE EVENTO_ESCOLAR

USE EVENTO_ESCOLAR

--table evento

CREATE TABLE EVENTO
(
COD_EVENTO INT NOT NULL IDENTITY (1,1),
DURACAO TIME NOT NULL,
TITULO VARCHAR(45) NOT NULL,
DESCRICAO VARCHAR(500),
DATA_EVENTO DATE NOT NULL,
HORARIO TIME NOT NULL,
CONSTRAINT PK_EVENTO PRIMARY KEY (COD_EVENTO)
)

--table perfil

CREATE TABLE PERFIL
(
COD_PERFIL INT NOT NULL IDENTITY (1,1),
DESCRICAO VARCHAR(45) NOT NULL,
CONSTRAINT PK_PERFIL PRIMARY KEY (COD_PERFIL)
)

--table usuario

CREATE TABLE USUARIO
(
COD_USUARIO INT NOT NULL IDENTITY (1,1),
NOME VARCHAR(45) NOT NULL,
EMAIL VARCHAR(45) NOT NULL,
SENHA VARBINARY,
TELEFONE CHAR(8) NOT NULL,
CELLULAR CHAR(9),
COD_PERFIL INT,
CONSTRAINT PK_USUARIO PRIMARY KEY (COD_USUARIO),
CONSTRAINT FK_PERFIL_U FOREIGN KEY (COD_PERFIL) REFERENCES PERFIL (COD_PERFIL)
)

--table inscricao

CREATE TABLE INSCRICAO
(
COD_INSCRICAO INT NOT NULL IDENTITY (1,1),
COD_USUARIO INT,
DATA_HORA_INSC DATETIME NOT NULL,
DATA_HORA_PARTICIPACAO DATETIME NOT NULL,
COD_EVENTO INT,
QRCODE INT,
CONSTRAINT PK_INSCRICAO PRIMARY KEY (COD_INSCRICAO),
CONSTRAINT FK_USUARIO_INSC FOREIGN KEY (COD_USUARIO) REFERENCES USUARIO (COD_USUARIO),
CONSTRAINT FK_EVENTO_INSC FOREIGN KEY (COD_EVENTO) REFERENCES EVENTO (COD_EVENTO)
)

--table feedback

CREATE TABLE FEEDBACK
(
COD_FEEDBACK INT NOT NULL IDENTITY (1,1),
COMENTARIO VARCHAR(500),
NOTA CHAR(5),
COD_INSCRICAO INT,
COD_EVENTO INT,
CONSTRAINT PK_FEEDBACK PRIMARY KEY (COD_FEEDBACK),
CONSTRAINT FK_INSCRICAO_FEED FOREIGN KEY (COD_INSCRICAO) REFERENCES INSCRICAO (COD_INSCRICAO),
CONSTRAINT FK_EVENTO_FEED FOREIGN KEY (COD_EVENTO) REFERENCES EVENTO (COD_EVENTO)
)

--table usuario_gerencia_evento

CREATE TABLE USUARIO_GERENCIA_EVENTO
(
COD_GERENCIA INT NOT NULL IDENTITY (1,1),
COD_USUARIO INT,
COD_EVETO INT, --ALTER PARA ADICNIONAR CAMPO
CONSTRAINT PK_GERENCIA PRIMARY KEY (COD_GERENCIA),
CONSTRAINT FK_USUARIO_GEREN FOREIGN KEY (COD_USUARIO) REFERENCES USUARIO (COD_USUARIO),
CONSTRAINT FK_GEREN_EVENTO FOREIGN KEY (COD_EVENTO) REFERENCES EVENTO (COD_EVENTO) -- ALTER PARA ADICIONAR CONSTRAINT
)

SELECT * FROM USUARIO_GERENCIA_EVENTO

alter table USUARIO_GERENCIA_EVENTO
add COD_EVETO INT,
CONSTRAINT FK_EVENTO_GEREN FOREIGN KEY (COD_EVENTO) REFERENCES EVENTO (COD_EVENTO)