-- busca de usuarios a partir do id de perfil
SELECT USUARIO.COD_PERFIL, USUARIO.NOME,
PERFIL.COD_PERFIL, PERFIL.DESCRICAO
FROM USUARIO INNER JOIN
PERFIL ON USUARIO.COD_PERFIL = PERFIL.COD_PERFIL
WHERE DESCRICAO = 'Auxiliar de Eventos'