USE EVENTO_ESCOLAR


-- Inserindo a colua COD_EVENTO na tabela USUARIO_GERENCIA_EVENTO
ALTER TABLE USUARIO_GERENCIA_EVENTO
ADD COD_EVETO INT,
CONSTRAINT FK_EVENTO_GEREN FOREIGN KEY (COD_EVENTO) REFERENCES EVENTO (COD_EVENTO)

-- JOIN para USUARIO e PERFIL
SELECT USUARIO.NOME, PERFIL.DESCRICAO
FROM USUARIO INNER JOIN PERFIL
ON USUARIO.COD_USUARIO = PERFIL.COD_PERFIL
WHERE PERFIL.DESCRICAO = 'Aluno'

-- VIEW para USUARIO com o PERFIL Aluno
CREATE VIEW VW_SUARIO AS
SELECT USUARIO.NOME, PERFIL.DESCRICAO
FROM USUARIO INNER JOIN PERFIL
ON USUARIO.COD_USUARIO = PERFIL.COD_PERFIL
WHERE PERFIL.DESCRICAO = 'Aluno'

-- JOIN para visualizar os participantes do evento
SELECT USUARIO.NOME, INSCRICAO.DATA_HORA_PARTICIPACAO
FROM USUARIO INNER JOIN INSCRICAO
ON USUARIO.COD_USUARIO = INSCRICAO.COD_INSCRICAO
WHERE INSCRICAO.DATA_HORA_PARTICIPACAO

SELECT * FROM USUARIO_GERENCIA_EVENTO